name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    # - name: Python Pylin GitHub Action
    #   uses: fylein/python-pylint-github-action@v1
    #   with:
    #     args: pip install -r src/requirements.txt && pylint --rcfile=pylintrc ./src/main.py
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        image: ${{ secrets.DOCKER_USERNAME }}/chombybot

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
        repository: 'GridLAN/k8s'

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.6.1"

    - name: Update Kubernetes resources
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
       cd applications/chomby/kustomize/base
       kustomize edit set image chombybot=$DOCKER_USERNAME/chombybot:$GITHUB_REF
       cat kustomization.yaml
        
    - name: Commit files
      run: |
        git config --local user.email "git-action-deploy@github.com"
        git config --local user.name "git-action-bot"
        git commit -am "Bump docker tag"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT_FOR_PUSH }}
        repository: 'GridLAN/k8s'
# comment
